"""empty message

Revision ID: 46925d674d7d
Revises: 3f9bc4d2e416
Create Date: 2014-04-27 18:30:36.890654

"""

# revision identifiers, used by Alembic.
revision = '46925d674d7d'
down_revision = '3f9bc4d2e416'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_superuser')
    ### end Alembic commands ###
