"""sessions, conversation shares, scopes, chunk offsets

Revision ID: bde95b2679fe
Revises: 0aba938134d5
Create Date: 2026-04-30 21:32:52.852595
"""
from alembic import op
import sqlalchemy as sa


revision = 'bde95b2679fe'
down_revision = '0aba938134d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('session_token_hash', sa.String(length=128), nullable=False),
    sa.Column('user_agent', sa.String(length=512), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_session_session_token_hash'), 'user_session', ['session_token_hash'], unique=True)
    op.create_index(op.f('ix_user_session_user_id'), 'user_session', ['user_id'], unique=False)
    op.create_table('conversation_share_link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=True),
    sa.Column('token', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_share_link_conversation_id'), 'conversation_share_link', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_conversation_share_link_token'), 'conversation_share_link', ['token'], unique=True)
    op.add_column('api_key', sa.Column('scopes_json', sa.Text(), nullable=True))
    op.add_column('chunk', sa.Column('char_offset_start', sa.Integer(), nullable=True))
    op.add_column('chunk', sa.Column('char_offset_end', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunk', 'char_offset_end')
    op.drop_column('chunk', 'char_offset_start')
    op.drop_column('api_key', 'scopes_json')
    op.drop_index(op.f('ix_conversation_share_link_token'), table_name='conversation_share_link')
    op.drop_index(op.f('ix_conversation_share_link_conversation_id'), table_name='conversation_share_link')
    op.drop_table('conversation_share_link')
    op.drop_index(op.f('ix_user_session_user_id'), table_name='user_session')
    op.drop_index(op.f('ix_user_session_session_token_hash'), table_name='user_session')
    op.drop_table('user_session')
    # ### end Alembic commands ###
